name       : flightgear-data
version    : 2020.3.18
release    : 11
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2020.3/FlightGear-2020.3.18-data.txz : 53c96c1ebc38d17a3a6b78d9c3a1a23e73802efbe0f4f75e71501d9197b05238
homepage   : https://www.flightgear.org/
license    : GPL-2.0-or-later
component  : games
summary    : FlightGear data and assets
description: |
    FlightGear is an open-source flight simulator. This package contains data and assets necessary to run the simulator.
extract    : no
install    : |
    install -dm00644 $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.txz --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
    rm -rf $installdir/usr/share/flightgear/{AUTHORS,ChangeLog,COPYING,NEWS,Readme*,Thanks}
