name       : flightgear-data
version    : 2018.3.5
release    : 1
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2018.3/FlightGear-2018.3.5-data.tar.bz2 : 13725d5e628ce2feb3f102b744fffe4a0e2a8847a74b039da7ddd35fd44fdb11
license    : GPL-2.0-or-later
component  : games
homepage   : https://www.flightgear.org/
summary    : FlightGear data and assets
description: |
    FlightGear is an open-source flight simulator. This package contains data and assets necessary to run the simulator.
extract    : no
install    : |
    mkdir -p $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
