name       : flightgear-data
version    : 2020.3.5
release    : 5
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2020.3/FlightGear-2020.3.5-data.tar.bz2 : 3acc7f7d21d4013dd8251d798b01fdcbede9e116482ae9adaa1517fe8b0765d9
license    : GPL-2.0-or-later
component  : games
homepage   : https://www.flightgear.org/
summary    : FlightGear data and assets
description: |
    FlightGear is an open-source flight simulator. This package contains data and assets necessary to run the simulator.
extract    : no
install    : |
    install -dm00644 $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
