name       : flightgear-data
version    : 2020.3.13
release    : 9
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2020.3/FlightGear-2020.3.13-data.txz : 0b7894540ec8250efb39d5dc6819d2a43a613058e61599a7d27a3342f7714893
homepage   : https://www.flightgear.org/
license    : GPL-2.0-or-later
component  : games
summary    : FlightGear data and assets
description: |
    FlightGear is an open-source flight simulator. This package contains data and assets necessary to run the simulator.
extract    : no
install    : |
    install -dm00644 $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.txz --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
    rm -rf $installdir/usr/share/flightgear/{AUTHORS,ChangeLog,COPYING,NEWS,Readme*,Thanks}
